### ISSUE TITLE
Type 'string[]' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by dasixi34** [clvs7-gh/rec0bot-plugin-ldap-bridge#1]
デプロイの際に以下のエラーが出ました。
`string`を`string[]`に変えるだけだと思いますが、pushできないようなので、issueで投げさせていただきます。
```
index.ts(58,21): error TS2322: Type 'string | string[]' is not assignable to type 'string'.
  Type 'string[]' is not assignable to type 'string'.
index.ts(59,21): error TS2322: Type 'string | string[]' is not assignable to type 'string'.
  Type 'string[]' is not assignable to type 'string'.
```
https://github.com/clvs7-gh/rec0bot-plugin-ldap-bridge/blob/72d4398ce7b4f88a3ad4276dfb752a83ae7dd44d/index.ts#L15-L18
https://github.com/clvs7-gh/rec0bot-plugin-ldap-bridge/blob/72d4398ce7b4f88a3ad4276dfb752a83ae7dd44d/index.ts#L58-L59

**Comment by clvs7-gh** [comment]
Username and fullname is must be `string`, not `string[]`.
`entry.object.sAMAccountName`, `entry.object.displayName`, `entry.object.cn` are should be `string`, so casting these objects to `string` is desirable answer.

Solved by caca8212ecfb2fba48d0bdc4ab8a434e177b6a89.
